# SPDX-FileCopyrightText: 2019 John Irle
#
# SPDX-License-Identifier: MIT

name: check
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://npm.pkg.github.com
      - run: npm install
      - run: npm test
